development:
  bucket_name: tracks.development
  access_key_id:  0VE4BRYDMSRHYG0X93R2
  secret_access_key: a6W0PzS9MydgO//TQua0ooOx7YI+RkjWOOfUqcv8

test:
  bucket_name: tracks.development
  access_key_id:  0VE4BRYDMSRHYG0X93R2
  secret_access_key: a6W0PzS9MydgO//TQua0ooOx7YI+RkjWOOfUqcv8

production:
  bucket_name: tracks.production
  access_key_id:  0VE4BRYDMSRHYG0X93R2
  secret_access_key: a6W0PzS9MydgO//TQua0ooOx7YI+RkjWOOfUqcv8
