development:
  adapter: mysql
  database: tracks
  host: localhost
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  database: tracks
  username: 
  password:  
  host: localhost

production:
  adapter: mysql
  database: tracks
  host: localhost
  username: root
  password: